drop table board if exists;
drop table card if exists;
drop table comment if exists;
drop table customer if exists;
drop table deck if exists;
drop table user if exists;

create table board (board_id bigint generated by default as identity, name varchar(255) not null, primary key (board_id));
create table comment (comment_id bigint generated by default as identity, card_id bigint not null, 
content varchar(255), created_time varchar(255), writer varchar(255), primary key (comment_id));
create table customer (id bigint generated by default as identity, first_name varchar(255), 
last_name varchar(255), primary key (id));
create table deck (deck_id bigint generated by default as identity, deck_name varchar(255) not null, 
board_id bigint, primary key (deck_id));
create table user (id bigint generated by default as identity, email varchar(255) not null, 
password varchar(255) not null, user_name varchar(255) not null, primary key (id));
alter table deck add constraint FK_t2i7ntbuepn4lqi38ncxx84r7 foreign key (board_id) references board;

